# Generated by Django 4.2 on 2026-09-22 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token_last_expired',
            field=models.DateTimeField(null=True),
        ),
    ]
